# Generated by Django 4.1 on 2023-03-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0002_relationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
                ("duration", models.DurationField()),
                ("startdate", models.DateField()),
                ("completiondate", models.DateField()),
                ("cost", models.FloatField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "uncompleted"), (1, "completed")], default=0
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="profiles.profile",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
    ]
