# Generated by Django 4.1 on 2023-03-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
